baseURL = "https://ishabangla.github.io/SMElectronics/"
publishDir = "docs"
languageCode = "en-us"
title = "SM Electronics"
theme = "paper"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

